version: '3.0'
services:
  postgres:
    image: postgres:15
    container_name: postgres_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hourmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-services

networks:
  dev-services:

volumes:
  postgres_data: